/*
 * Created on 09.08.2013
 *
 * Copyright(c) 2011 - 2013 T-Systems Multimedia Solutions GmbH
 * Riesaer Str. 5, 01129 Dresden
 * All rights reserved.
 */
package eu.tsystems.mms.tic.testframework.qcrest.test.client;

import eu.tsystems.mms.tic.testframework.qcrest.clients.QcRestClient;
import eu.tsystems.mms.tic.testframework.qcrest.clients.RestConnector;
import eu.tsystems.mms.tic.testframework.qcrest.wrapper.TestPlanFolder;
import eu.tsystems.mms.tic.testframework.qcrest.wrapper.TestPlanTest;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.testng.Assert;
import org.testng.annotations.Test;

import java.io.IOException;
import java.util.HashMap;
import java.util.Map;

/**
 * Tests for QC Test Plan.
 * 
 * @author sepr
 * 
 */
public class PlanTest extends AbstractTest {

    /** Logger */
    private static final Logger LOG = LoggerFactory.getLogger(PlanTest.class);
    /** Path to test in testlab. */
    private static final String TEST_PATH = "Subject\\Xeta\\QCWebServiceClient";
    /** Trash Folder. */
    private static final String TRASH = "TrashCan";
    /** Name of tests in testlab */
    private static final String TEST = "testUnderTest";

    /**
     * Test method: change the properties of an existing Test in QC TestPlan.
     * 
     * @throws IOException .
     */
    @Test
    public void testEditTest() throws IOException {

        LOG.info("Test editTest");
        final TestPlanTest test = QcRestClient.getTestPlanTest(TEST, TEST_PATH);
        LOG.debug("Test description before: " + test.getDescription());

        // To edit a test, create an empty entity and set its id and the changed values.
        // Real objects from the service contain too much information.
        final TestPlanTest changer = new TestPlanTest();
        final Long timestamp = System.currentTimeMillis();
        changer.setDescription(timestamp + "");
        LOG.debug("Set Test description to: " + changer.getDescription());
        QcRestClient.editTest(changer, test.getId());

        LOG.debug("Getting updated test.");
        final TestPlanTest validate = QcRestClient.getTestPlanTest(TEST, TEST_PATH);
        LOG.debug("Updated Test description: " + validate.getDescription());
        Assert.assertTrue(validate.getDescription().contains(timestamp + ""), "Test doesn't seem to be changed");
    }

    /**
     * Test method: gets a test under a specified path.
     * 
     * @throws IOException RestException
     */
    @Test(enabled = true)
    public void testGetTest() throws IOException {
        LOG.info("Get test from Plan");
        final TestPlanTest test = QcRestClient.getTestPlanTest(TEST, TEST_PATH);
        LOG.debug("Test name       : " + test.getName());
        LOG.debug("Test description: " + test.getDescription());
        LOG.debug("Test path       : " + test.getPath());
        LOG.debug("Test id         : " + test.getId());
        LOG.debug("Test type       : " + test.getType());

        Assert.assertEquals(TEST, test.getName());
    }

    /**
     * Test method: change the properties of an existing Test in QC TestPlan.
     * 
     * @throws IOException .
     */
    @Test
    public void testAddTest() throws IOException {
        TestPlanFolder parent = null;
        int idReturned = 0;
        try {
            testCreateTestPlanFolder();
            LOG.info("Test addTest");
            final String time = System.currentTimeMillis() + "";
            parent = QcRestClient.getTestPlanFolder(TEST_PATH + "\\" + TRASH);
            final TestPlanTest test = new TestPlanTest();
            test.setDescription("Test generated by QcRestClient for test purposes. Remove if you want to.");
            test.setName(time);
            test.setParentId(parent.getId());
            test.setType("MANUAL");
            idReturned = QcRestClient.addTest(test);
            Assert.assertNotEquals(idReturned, 0, "Returned id is 0, so something went wrong.");

            LOG.debug("Getting created test.");
            final TestPlanTest validate = QcRestClient.getTestPlanTestById(idReturned);
            LOG.debug("Added Test: " + validate.toString());
        } finally {
            // delete
            if (idReturned != 0) {
                LOG.debug("Remove created test");
                Map<String, String> requestHeaders = new HashMap<String, String>();
                requestHeaders.put("Accept", "application/xml");
                RestConnector.getInstance().httpDelete(
                        RestConnector.getInstance().buildEntityCollectionUrl("test") + "/" + idReturned)
                        .toString();
            }
            parent = QcRestClient.getTestPlanFolder(TEST_PATH + "\\" + TRASH);
            if (parent != null) {
                LOG.debug("Remove created Folder");
                Map<String, String> requestHeaders = new HashMap<String, String>();
                requestHeaders.put("Accept", "application/xml");
                RestConnector.getInstance().httpDelete(
                        RestConnector.getInstance().buildEntityCollectionUrl("test-folder") + "/" + parent.getId())
                        .toString();
            }
        }
    }

    /**
     * Create Trash Folder for addTest Tests.
     * 
     * @throws IOException .
     */
    private void testCreateTestPlanFolder() throws IOException {
        LOG.info("Test createTestPlanFolder");
        final TestPlanFolder parent = QcRestClient.getTestPlanFolder(TEST_PATH);
        final TestPlanFolder toCreate = new TestPlanFolder();
        toCreate.setName(TRASH);
        toCreate.setParentId(parent.getId());

        int idReturned = QcRestClient.createTestFolder(toCreate);
        Assert.assertNotEquals(idReturned, 0, "Returned id is 0, so something went wrong.");

        LOG.debug("Getting created Folder.");
        final TestPlanFolder validate = QcRestClient.getTestPlanFolderById(idReturned);
        LOG.debug("Added Test-Folder: " + validate.toString());
    }
}
